language: node_js
services:
  - Firebase
node_js:
  - "11.10.0"
before_install:
  - cd barter-web-app
  - npm i -g npm@6.7.0
install:
  - npm install
script:
  - npm run test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
